version: '3.3'
services:
  db:
    env_file:
        - env/dockerENVs
    image: mysql
    volumes:
        - dbdata:/var/lib/mysql
    restart: always
    ports:
        - "127.0.0.1:3306:3306"
  django:
    depends_on:
        - db
    env_file:
        - env/dockerENVs
    build:
        context: .
        dockerfile: ./docker/django/Dockerfile
    volumes:
        - .:/code
    ports:
        - "127.0.0.1:8081:8081"
    expose:
        - "8081"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        - PMA_ARBITRARY=1
    restart: always
    ports:
        - "127.0.0.1:8082:80"
    volumes:
        - /sessions
  nginx:
    build:
        context: ./docker/nginx/
        dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:8090:8090"
    depends_on:
      - django

volumes:
  dbdata:
